#!/usr/bin/env bash
set -e

readonly OPTIONS=/data/options.json
readonly CONFIG=/data/mediamtx.yml

log()  { echo "[mediamtx] $*"; }
opt()  { jq -r "$1 // empty" "${OPTIONS}"; }
bool() { local v; v=$(jq -r "$1" "${OPTIONS}"); [[ "${v}" == "true" ]] && echo "true" || echo "false"; }

# ── generate mediamtx.yml ─────────────────────────────────────────────────────

log "Generating MediaMTX configuration..."

cat > "${CONFIG}" <<YAML
# Generated by the MediaMTX Home Assistant add-on.
# Changes are overwritten on every restart – edit via the add-on Configuration tab.

logLevel: $(opt '.log_level')
logDestinations: [stdout]

rtsp: $(bool '.rtsp')
rtspAddress: :8554
rtspTransports: [$(opt '.rtsp_transports // "udp,multicast,tcp"')]

rtmp: $(bool '.rtmp')
rtmpAddress: :1935

hls: $(bool '.hls')
hlsAddress: :8888
hlsAlwaysRemux: $(bool '.hls_always_remux')

webrtc: $(bool '.webrtc')
webrtcAddress: :8889
webrtcLocalUDPAddress: :8189

srt: $(bool '.srt')
srtAddress: :8890

api: $(bool '.api')
apiAddress: :9997

YAML

# ── authentication ────────────────────────────────────────────────────────────

AUTH_ENABLED=$(jq -r '.auth_enabled' "${OPTIONS}")

if [[ "${AUTH_ENABLED}" == "true" ]]; then
    PUBLISH_USER=$(opt '.publish_user')
    PUBLISH_PASS=$(opt '.publish_pass')
    READ_USER=$(opt '.read_user')
    READ_PASS=$(opt '.read_pass')

    if [[ -z "${READ_USER}" ]]; then
        READ_USER="${PUBLISH_USER}"
        READ_PASS="${PUBLISH_PASS}"
    fi

    log "Authentication enabled (publish user: ${PUBLISH_USER})"

    cat >> "${CONFIG}" <<YAML
authMethod: internal
authInternalUsers:
  - user: ${PUBLISH_USER}
    pass: ${PUBLISH_PASS}
    ips: []
    permissions:
      - action: publish
        path:
  - user: ${READ_USER}
    pass: ${READ_PASS}
    ips: []
    permissions:
      - action: read
        path:
      - action: playback
        path:
  - user: any
    pass:
    ips: ['127.0.0.1', '::1']
    permissions:
      - action: api
      - action: metrics
      - action: pprof

YAML
else
    log "Authentication disabled (all clients accepted)"

    cat >> "${CONFIG}" <<'YAML'
authMethod: internal
authInternalUsers:
  - user: any
    pass:
    ips: []
    permissions:
      - action: publish
        path:
      - action: read
        path:
      - action: playback
        path:
  - user: any
    pass:
    ips: ['127.0.0.1', '::1']
    permissions:
      - action: api
      - action: metrics
      - action: pprof

YAML
fi

# ── path defaults (recording) ─────────────────────────────────────────────────

RECORD=$(bool '.record')
RECORD_PATH=$(opt '.record_path')
RECORD_FORMAT=$(opt '.record_format')
RECORD_DELETE_AFTER=$(opt '.record_delete_after')

cat >> "${CONFIG}" <<YAML
pathDefaults:
  record: ${RECORD}
  recordPath: ${RECORD_PATH}
  recordFormat: ${RECORD_FORMAT}
  recordDeleteAfter: ${RECORD_DELETE_AFTER}

YAML

# ── custom config override ────────────────────────────────────────────────────

CUSTOM=$(opt '.custom_config')
if [[ -n "${CUSTOM}" ]]; then
    log "Appending custom configuration block..."
    printf '\n%s\n' "${CUSTOM}" >> "${CONFIG}"
fi

# ── paths ─────────────────────────────────────────────────────────────────────

printf '\npaths:\n' >> "${CONFIG}"

PATHS_COUNT=$(jq '.paths | length' "${OPTIONS}")

if [[ "${PATHS_COUNT}" -gt 0 ]]; then
    # Only write a field if it is non-empty/non-null
    wf() { [[ -n "$2" ]] && printf '    %s: %s\n' "$1" "$2" >> "${CONFIG}"; }

    while IFS= read -r path_json; do
        pj() { printf '%s' "${path_json}" | jq -r "$1"; }
        pjopt() { printf '%s' "${path_json}" | jq -r "$1 // empty"; }

        NAME=$(pj '.name')
        printf '  %s:\n' "${NAME}" >> "${CONFIG}"

        wf source                      "$(pjopt '.source')"
        wf sourceFingerprint           "$(pjopt '.source_fingerprint')"
        wf sourceOnDemand              "$(pjopt '.source_on_demand')"
        wf sourceOnDemandStartTimeout  "$(pjopt '.source_on_demand_start_timeout')"
        wf sourceOnDemandCloseAfter    "$(pjopt '.source_on_demand_close_after')"
        wf maxReaders                  "$(pjopt '.max_readers')"
        wf overridePublisher           "$(pjopt '.override_publisher')"
        wf rtspTransport               "$(pjopt '.rtsp_transport')"
        wf rtspAnyPort                 "$(pjopt '.rtsp_any_port')"
        wf rtspRangeType               "$(pjopt '.rtsp_range_type')"
        wf rtspRangeStart              "$(pjopt '.rtsp_range_start')"
        wf sourceRedirect              "$(pjopt '.source_redirect')"
        wf record                      "$(pjopt '.record')"
        wf recordPath                  "$(pjopt '.record_path')"
        wf recordFormat                "$(pjopt '.record_format')"
        wf recordPartDuration          "$(pjopt '.record_part_duration')"
        wf recordSegmentDuration       "$(pjopt '.record_segment_duration')"
        wf recordDeleteAfter           "$(pjopt '.record_delete_after')"
        wf runOnInit                   "$(pjopt '.run_on_init')"
        wf runOnInitRestart            "$(pjopt '.run_on_init_restart')"
        wf runOnDemand                 "$(pjopt '.run_on_demand')"
        wf runOnDemandRestart          "$(pjopt '.run_on_demand_restart')"
        wf runOnDemandStartTimeout     "$(pjopt '.run_on_demand_start_timeout')"
        wf runOnDemandCloseAfter       "$(pjopt '.run_on_demand_close_after')"
        wf runOnReady                  "$(pjopt '.run_on_ready')"
        wf runOnReadyRestart           "$(pjopt '.run_on_ready_restart')"
        wf runOnRead                   "$(pjopt '.run_on_read')"
        wf runOnReadRestart            "$(pjopt '.run_on_read_restart')"
    done < <(jq -c '.paths[]' "${OPTIONS}")
else
    printf '  all_others:\n' >> "${CONFIG}"
fi

log "Configuration written to ${CONFIG}"
log "Starting MediaMTX..."

exec /mediamtx "${CONFIG}"
