#!/usr/bin/env bash
set -e

readonly OPTIONS=/data/options.json
readonly CONFIG=/data/mediamtx.yml

log()  { echo "[mediamtx] $*"; }
opt()  { jq -r "$1 // empty" "${OPTIONS}"; }
bool() { local v; v=$(jq -r "$1" "${OPTIONS}"); [[ "${v}" == "true" ]] && echo "true" || echo "false"; }

# ── generate mediamtx.yml ─────────────────────────────────────────────────────

log "Generating MediaMTX configuration..."

cat > "${CONFIG}" <<YAML
# Generated by the MediaMTX Home Assistant add-on.
# Changes are overwritten on every restart – edit via the add-on Configuration tab.

logLevel: $(opt '.log_level')
logDestinations: [stdout]

rtsp: $(bool '.rtsp')
rtspAddress: :8554

rtmp: $(bool '.rtmp')
rtmpAddress: :1935

hls: $(bool '.hls')
hlsAddress: :8888
hlsAlwaysRemux: $(bool '.hls_always_remux')

webrtc: $(bool '.webrtc')
webrtcAddress: :8889
webrtcLocalUDPAddress: :8189

srt: $(bool '.srt')
srtAddress: :8890

api: $(bool '.api')
apiAddress: :9997

YAML

# ── authentication ────────────────────────────────────────────────────────────

AUTH_ENABLED=$(jq -r '.auth_enabled' "${OPTIONS}")

if [[ "${AUTH_ENABLED}" == "true" ]]; then
    PUBLISH_USER=$(opt '.publish_user')
    PUBLISH_PASS=$(opt '.publish_pass')
    READ_USER=$(opt '.read_user')
    READ_PASS=$(opt '.read_pass')

    if [[ -z "${READ_USER}" ]]; then
        READ_USER="${PUBLISH_USER}"
        READ_PASS="${PUBLISH_PASS}"
    fi

    log "Authentication enabled (publish user: ${PUBLISH_USER})"

    cat >> "${CONFIG}" <<YAML
authMethod: internal
authInternalUsers:
  - user: ${PUBLISH_USER}
    pass: ${PUBLISH_PASS}
    ips: []
    permissions:
      - action: publish
        path:
  - user: ${READ_USER}
    pass: ${READ_PASS}
    ips: []
    permissions:
      - action: read
        path:
      - action: playback
        path:
  - user: any
    pass:
    ips: ['127.0.0.1', '::1']
    permissions:
      - action: api
      - action: metrics
      - action: pprof

YAML
else
    log "Authentication disabled (all clients accepted)"

    cat >> "${CONFIG}" <<'YAML'
authMethod: internal
authInternalUsers:
  - user: any
    pass:
    ips: []
    permissions:
      - action: publish
        path:
      - action: read
        path:
      - action: playback
        path:
  - user: any
    pass:
    ips: ['127.0.0.1', '::1']
    permissions:
      - action: api
      - action: metrics
      - action: pprof

YAML
fi

# ── path defaults (recording) ─────────────────────────────────────────────────

RECORD=$(bool '.record')
RECORD_PATH=$(opt '.record_path')
RECORD_FORMAT=$(opt '.record_format')
RECORD_DELETE_AFTER=$(opt '.record_delete_after')

cat >> "${CONFIG}" <<YAML
pathDefaults:
  record: ${RECORD}
  recordPath: ${RECORD_PATH}
  recordFormat: ${RECORD_FORMAT}
  recordDeleteAfter: ${RECORD_DELETE_AFTER}

YAML

# ── custom config override ────────────────────────────────────────────────────

CUSTOM=$(opt '.custom_config')
if [[ -n "${CUSTOM}" ]]; then
    log "Appending custom configuration block..."
    printf '\n%s\n' "${CUSTOM}" >> "${CONFIG}"
fi

# ── paths ─────────────────────────────────────────────────────────────────────

printf '\npaths:\n' >> "${CONFIG}"

PATHS_COUNT=$(jq '.paths | length' "${OPTIONS}")

if [[ "${PATHS_COUNT}" -gt 0 ]]; then
    while IFS= read -r path_json; do
        NAME=$(printf '%s' "${path_json}" | jq -r '.name')
        SOURCE=$(printf '%s' "${path_json}" | jq -r '.source // empty')
        SOURCE_ON_DEMAND=$(printf '%s' "${path_json}" | jq -r '.source_on_demand')
        PATH_RECORD=$(printf '%s' "${path_json}" | jq -r '.record')

        printf '  %s:\n' "${NAME}" >> "${CONFIG}"

        if [[ -n "${SOURCE}" ]]; then
            printf '    source: %s\n'        "${SOURCE}"           >> "${CONFIG}"
            printf '    sourceOnDemand: %s\n' "${SOURCE_ON_DEMAND}" >> "${CONFIG}"
        fi

        printf '    record: %s\n' "${PATH_RECORD}" >> "${CONFIG}"
    done < <(jq -c '.paths[]' "${OPTIONS}")
else
    printf '  all_others:\n' >> "${CONFIG}"
fi

log "Configuration written to ${CONFIG}"
log "Starting MediaMTX..."

exec /mediamtx "${CONFIG}"
